In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

C:\Users\bhavy\anaconda3\Lib\site-packages\pandas\core\computation\expressions.py:22: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.10.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [2]:
df = pd.read_csv('train.csv')

In [3]:
df.shape

(404290, 6)

In [4]:
df.head()

,id,qid1,qid2,question1,question2,is_duplicate
0,0,1,2,What is the step by step guide to invest in sh...,What is the step by step guide to invest in sh...,0
1,1,3,4,What is the story of Kohinoor (Koh-i-Noor) Dia...,What would happen if the Indian government sto...,0
2,2,5,6,How can I increase the speed of my internet co...,How can Internet speed be increased by hacking...,0
3,3,7,8,Why am I mentally very lonely? How can I solve...,Find the remainder when [math]23^{24}[/math] i...,0
4,4,9,10,"Which one dissolve in water quikly sugar, salt...",Which fish would survive in salt water?,0

In [5]:
new_df = df.sample(30000)

In [6]:
new_df.isnull().sum()

id              0
qid1            0
qid2            0
question1       0
question2       0
is_duplicate    0
dtype: int64

In [7]:
new_df.duplicated().sum()

np.int64(0)

In [8]:
ques_df = new_df[['question1','question2']]
ques_df.head()

,question1,question2
159361,What is the best answer to why should I not hi...,Why should we not hire you?
342642,How to hack Wifi?,Am How to hack and get the password of a wifi?
13647,How do you promote a group on Facebook organic...,How do I promote a Facebook group?
119946,What are some good laptops under 50k for gamin...,What are the 5 best laptops in india under 50k...
372437,Is following hadith together with the Qur’an c...,Does your pussy smell?

In [9]:
from sklearn.feature_extraction.text import CountVectorizer
# merge texts
questions = list(ques_df['question1']) + list(ques_df['question2'])

cv = CountVectorizer(max_features=3000)
q1_arr, q2_arr = np.vsplit(cv.fit_transform(questions).toarray(),2)

In [10]:
temp_df1 = pd.DataFrame(q1_arr, index = ques_df.index)
temp_df2 = pd.DataFrame(q2_arr, index = ques_df.index)
temp_df = pd.concat([temp_df1, temp_df2],axis=1)
temp_df.shape

(30000, 6000)

In [11]:
temp_df

,0,1,2,3,4,5,6,7,8,9,...,2990,2991,2992,2993,2994,2995,2996,2997,2998,2999
159361,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
342642,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13647,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
119946,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
372437,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375706,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
81356,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
210094,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
235407,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
302121,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [12]:
temp_df['is_duplicate'] = new_df['is_duplicate']

In [13]:
temp_df.head()

,0,1,2,3,4,5,6,7,8,9,...,2991,2992,2993,2994,2995,2996,2997,2998,2999,is_duplicate
159361,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
342642,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
13647,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
119946,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
372437,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0

In [14]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(temp_df.iloc[:,0:-1].values,temp_df.iloc[:,-1].values,test_size=0.2,random_state=1)

In [17]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
rf = RandomForestClassifier()
rf.fit(X_train,y_train)
y_pred = rf.predict(X_test)
accuracy_score(y_test,y_pred)

0.7381666666666666

In [18]:
from xgboost import XGBClassifier
xgb = XGBClassifier()
xgb.fit(X_train,y_train)
y_pred = xgb.predict(X_test)
accuracy_score(y_test,y_pred)

0.7238333333333333